import type { Event } from '@/lib/types/event-domain';

export const seedEvents: Event[] = [
  {
    id: '1',
    name: 'Festa de São João',
    description:
      'A maior festa junina da comunidade! Venha celebrar com comidas típicas, jogos e muita diversão.',
    date: '2026-06-24',
    startTime: '18:00',
    endTime: '23:00',
    location: 'Paróquia São João Batista',
    cityId: 'curitiba-pr',
    organizerId: 'org-paroquia',
    banner: '/festa-banner.jpg',
    status: 'active',
    capacity: 500,
    primaryColor: '#d97706',
    icon: '🎪',
  },
  {
    id: '2',
    name: 'Festa de Natal',
    description:
      'Celebração natalina com comidas típicas, doces e bebidas quentes para toda a família.',
    date: '2026-12-25',
    startTime: '17:00',
    endTime: '22:00',
    location: 'Salão Paroquial',
    cityId: 'curitiba-pr',
    organizerId: 'org-paroquia',
    banner: '/natal-banner.jpg',
    status: 'published',
    capacity: 300,
    primaryColor: '#dc2626',
    icon: '🎄',
  },
  {
    id: '3',
    name: 'Quermesse Comunitária',
    description: 'Festa beneficente com barracas, bingo e comidas típicas.',
    date: '2026-08-15',
    startTime: '19:00',
    endTime: '23:30',
    location: 'Centro Comunitário Norte',
    cityId: 'londrina-pr',
    organizerId: 'org-londrina',
    banner: '/festa-banner.jpg',
    status: 'published',
    capacity: 250,
    primaryColor: '#7c3aed',
    icon: '🎉',
  },
];
