import type { CatalogProduct } from '@/lib/types/event-domain';

export const seedCatalogProducts: CatalogProduct[] = [
  {
    id: 'pastel',
    name: 'Pastel',
    description: 'Pastel crocante frito na hora, recheado à sua escolha',
    category: 'comidas',
    image: '🥟',
    badge: 'Mais vendido',
    variantTemplates: [
      { id: 'carne', label: 'Carne' },
      { id: 'queijo', label: 'Queijo' },
    ],
  },
  {
    id: 'milho-verde',
    name: 'Milho Verde',
    description: 'Espiga de milho fresquinho com manteiga',
    category: 'comidas',
    image: '🌽',
    badge: 'Tradicional',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'cachorro-quente',
    name: 'Cachorro Quente',
    description: 'Pão, salsicha, molho, batata palha e muito mais',
    category: 'comidas',
    image: '🌭',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'espetinho-carne',
    name: 'Espetinho de Carne',
    description: 'Espetinho grelhado na hora, bem temperado',
    category: 'comidas',
    image: '🍢',
    badge: 'Popular',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'caldo-verde',
    name: 'Caldo Verde',
    description: 'Caldo quentinho de couve com linguiça',
    category: 'comidas',
    image: '🥣',
    variantTemplates: [{ id: 'copo', label: 'Copo' }],
  },
  {
    id: 'maca-amor',
    name: 'Maçã do Amor',
    description: 'Maçã coberta com calda vermelha crocante',
    category: 'doces',
    image: '🍎',
    badge: 'Clássico',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'canjica',
    name: 'Canjica',
    description: 'Canjica cremosa com canela e coco',
    category: 'doces',
    image: '🥛',
    variantTemplates: [{ id: 'copo', label: 'Copo' }],
  },
  {
    id: 'pacoca',
    name: 'Paçoca',
    description: 'Doce de amendoim tradicional',
    category: 'doces',
    image: '🥜',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'pe-de-moleque',
    name: 'Pé de Moleque',
    description: 'Rapadura com amendoim crocante',
    category: 'doces',
    image: '🍬',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'cocada',
    name: 'Cocada',
    description: 'Doce de coco caramelizado',
    category: 'doces',
    image: '🥥',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'quentao',
    name: 'Quentão',
    description: 'Bebida quente com gengibre e especiarias',
    category: 'bebidas',
    image: '🍵',
    badge: 'Esquenta!',
    variantTemplates: [{ id: 'copo', label: 'Copo' }],
  },
  {
    id: 'vinho-quente',
    name: 'Vinho Quente',
    description: 'Vinho temperado com canela e cravo',
    category: 'bebidas',
    image: '🍷',
    variantTemplates: [{ id: 'copo', label: 'Copo' }],
  },
  {
    id: 'refrigerante',
    name: 'Refrigerante',
    description: 'Lata 350ml gelada',
    category: 'bebidas',
    image: '🥤',
    variantTemplates: [
      { id: 'coca', label: 'Coca-Cola' },
      { id: 'guarana', label: 'Guaraná' },
      { id: 'fanta', label: 'Fanta Laranja' },
    ],
  },
  {
    id: 'agua-mineral',
    name: 'Água Mineral',
    description: 'Garrafa 500ml',
    category: 'bebidas',
    image: '💧',
    variantTemplates: [{ id: 'garrafa', label: 'Garrafa' }],
  },
  {
    id: 'suco-natural',
    name: 'Suco Natural',
    description: 'Copo 300ml feito na hora',
    category: 'bebidas',
    image: '🧃',
    variantTemplates: [
      { id: 'laranja', label: 'Laranja' },
      { id: 'limao', label: 'Limão' },
    ],
  },
  {
    id: 'pescaria',
    name: 'Pescaria',
    description: 'Pesque um peixe e ganhe um prêmio!',
    category: 'jogos',
    image: '🎣',
    badge: 'Diversão',
    variantTemplates: [{ id: 'jogada', label: 'Jogada' }],
  },
  {
    id: 'argolas',
    name: 'Argolas',
    description: 'Acerte as argolas e ganhe brindes',
    category: 'jogos',
    image: '🎯',
    variantTemplates: [{ id: 'jogada', label: 'Jogada' }],
  },
  {
    id: 'tiro-ao-alvo',
    name: 'Tiro ao Alvo',
    description: 'Teste sua pontaria!',
    category: 'jogos',
    image: '🎯',
    variantTemplates: [{ id: 'jogada', label: 'Jogada' }],
  },
  {
    id: 'bingo',
    name: 'Cartela de Bingo',
    description: 'Concorra a prêmios incríveis!',
    category: 'brincadeiras',
    image: '🎱',
    badge: 'Prêmios!',
    variantTemplates: [{ id: 'cartela', label: 'Cartela' }],
  },
  {
    id: 'correio-elegante',
    name: 'Correio Elegante',
    description: 'Envie uma mensagem secreta para alguém especial',
    category: 'brincadeiras',
    image: '💌',
    badge: 'Romântico',
    variantTemplates: [{ id: 'mensagem', label: 'Mensagem' }],
  },
  {
    id: 'quadrilha',
    name: 'Quadrilha',
    description: 'Participe da dança tradicional',
    category: 'brincadeiras',
    image: '💃',
    badge: 'Grátis',
    variantTemplates: [{ id: 'participacao', label: 'Participação' }],
  },
  {
    id: 'peru-assado',
    name: 'Peru Assado',
    description: 'Fatia generosa de peru assado com temperos natalinos',
    category: 'comidas',
    image: '🦃',
    badge: 'Especial',
    variantTemplates: [{ id: 'fatia', label: 'Fatia' }],
  },
  {
    id: 'panetone',
    name: 'Panetone',
    description: 'Fatia de panetone com frutas cristalizadas',
    category: 'doces',
    image: '🍞',
    variantTemplates: [{ id: 'fatia', label: 'Fatia' }],
  },
  {
    id: 'rabanada',
    name: 'Rabanada',
    description: 'Rabanada crocante com canela e açúcar',
    category: 'doces',
    image: '🍞',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
  {
    id: 'chocolate-quente',
    name: 'Chocolate Quente',
    description: 'Chocolate cremoso com marshmallow',
    category: 'bebidas',
    image: '☕',
    badge: 'Quentinho',
    variantTemplates: [{ id: 'copo', label: 'Copo' }],
  },
  {
    id: 'vinho-natal',
    name: 'Vinho Quente',
    description: 'Vinho temperado com especiarias natalinas',
    category: 'bebidas',
    image: '🍷',
    variantTemplates: [{ id: 'copo', label: 'Copo' }],
  },
  {
    id: 'sopa',
    name: 'Sopa de Mandioca',
    description: 'Sopa cremosa servida no copo',
    category: 'comidas',
    image: '🥣',
    variantTemplates: [{ id: 'copo', label: 'Copo' }],
  },
  {
    id: 'item-boas-vindas',
    name: 'Item de boas-vindas',
    description: 'Adicione mais itens pelo painel administrativo',
    category: 'comidas',
    image: '🍽️',
    variantTemplates: [{ id: 'unidade', label: 'Unidade' }],
  },
];

export function getCatalogProductById(productId: string): CatalogProduct | undefined {
  return seedCatalogProducts.find((product) => product.id === productId);
}
