import type { MenuProduct } from '@/lib/types/event-domain';

const menuProductsEvent1: Omit<MenuProduct, 'eventId'>[] = [
  {
    id: 'pastel',
    name: 'Pastel',
    description: 'Pastel crocante frito na hora, recheado à sua escolha',
    category: 'comidas',
    image: '🥟',
    badge: 'Mais vendido',
    available: true,
    stallId: 'stall-1',
    variants: [
      { id: 'pastel-carne', label: 'Carne', price: 8.0, available: true, badge: 'Mais vendido' },
      { id: 'pastel-queijo', label: 'Queijo', price: 7.0, available: true },
    ],
  },
  {
    id: 'milho-verde',
    name: 'Milho Verde',
    description: 'Espiga de milho fresquinho com manteiga',
    category: 'comidas',
    image: '🌽',
    badge: 'Tradicional',
    available: true,
    stallId: 'stall-2',
    variants: [{ id: 'milho-verde-unidade', label: 'Unidade', price: 6.0, available: true }],
  },
  {
    id: 'cachorro-quente',
    name: 'Cachorro Quente',
    description: 'Pão, salsicha, molho, batata palha e muito mais',
    category: 'comidas',
    image: '🌭',
    available: true,
    stallId: 'stall-2',
    variants: [{ id: 'cachorro-quente-unidade', label: 'Unidade', price: 10.0, available: true }],
  },
  {
    id: 'espetinho-carne',
    name: 'Espetinho de Carne',
    description: 'Espetinho grelhado na hora, bem temperado',
    category: 'comidas',
    image: '🍢',
    badge: 'Popular',
    available: true,
    stallId: 'stall-2',
    variants: [{ id: 'espetinho-carne-unidade', label: 'Unidade', price: 12.0, available: true }],
  },
  {
    id: 'caldo-verde',
    name: 'Caldo Verde',
    description: 'Caldo quentinho de couve com linguiça',
    category: 'comidas',
    image: '🥣',
    available: true,
    stallId: 'stall-2',
    variants: [{ id: 'caldo-verde-copo', label: 'Copo', price: 8.0, available: true }],
  },
  {
    id: 'maca-amor',
    name: 'Maçã do Amor',
    description: 'Maçã coberta com calda vermelha crocante',
    category: 'doces',
    image: '🍎',
    badge: 'Clássico',
    available: true,
    stallId: 'stall-3',
    variants: [{ id: 'maca-amor-unidade', label: 'Unidade', price: 8.0, available: true }],
  },
  {
    id: 'canjica',
    name: 'Canjica',
    description: 'Canjica cremosa com canela e coco',
    category: 'doces',
    image: '🥛',
    available: true,
    stallId: 'stall-3',
    variants: [{ id: 'canjica-copo', label: 'Copo', price: 7.0, available: true }],
  },
  {
    id: 'pacoca',
    name: 'Paçoca',
    description: 'Doce de amendoim tradicional',
    category: 'doces',
    image: '🥜',
    available: true,
    stallId: 'stall-3',
    variants: [{ id: 'pacoca-unidade', label: 'Unidade', price: 3.0, available: true }],
  },
  {
    id: 'pe-de-moleque',
    name: 'Pé de Moleque',
    description: 'Rapadura com amendoim crocante',
    category: 'doces',
    image: '🍬',
    available: true,
    stallId: 'stall-3',
    variants: [{ id: 'pe-de-moleque-unidade', label: 'Unidade', price: 4.0, available: true }],
  },
  {
    id: 'cocada',
    name: 'Cocada',
    description: 'Doce de coco caramelizado',
    category: 'doces',
    image: '🥥',
    available: true,
    stallId: 'stall-3',
    variants: [{ id: 'cocada-unidade', label: 'Unidade', price: 5.0, available: true }],
  },
  {
    id: 'quentao',
    name: 'Quentão',
    description: 'Bebida quente com gengibre e especiarias',
    category: 'bebidas',
    image: '🍵',
    badge: 'Esquenta!',
    available: true,
    stallId: 'stall-4',
    variants: [{ id: 'quentao-copo', label: 'Copo', price: 6.0, available: true }],
  },
  {
    id: 'vinho-quente',
    name: 'Vinho Quente',
    description: 'Vinho temperado com canela e cravo',
    category: 'bebidas',
    image: '🍷',
    available: true,
    stallId: 'stall-4',
    variants: [{ id: 'vinho-quente-copo', label: 'Copo', price: 8.0, available: true }],
  },
  {
    id: 'refrigerante',
    name: 'Refrigerante',
    description: 'Lata 350ml gelada',
    category: 'bebidas',
    image: '🥤',
    available: true,
    stallId: 'stall-4',
    variants: [
      { id: 'refrigerante-coca', label: 'Coca-Cola', price: 5.0, available: true },
      { id: 'refrigerante-guarana', label: 'Guaraná', price: 5.0, available: true },
      { id: 'refrigerante-fanta', label: 'Fanta Laranja', price: 5.0, available: true },
    ],
  },
  {
    id: 'agua-mineral',
    name: 'Água Mineral',
    description: 'Garrafa 500ml',
    category: 'bebidas',
    image: '💧',
    available: true,
    stallId: 'stall-4',
    variants: [{ id: 'agua-mineral-garrafa', label: 'Garrafa', price: 3.0, available: true }],
  },
  {
    id: 'suco-natural',
    name: 'Suco Natural',
    description: 'Copo 300ml feito na hora',
    category: 'bebidas',
    image: '🧃',
    available: true,
    stallId: 'stall-4',
    variants: [
      { id: 'suco-laranja', label: 'Laranja', price: 6.0, available: true },
      { id: 'suco-limao', label: 'Limão', price: 6.0, available: true },
    ],
  },
  {
    id: 'pescaria',
    name: 'Pescaria',
    description: 'Pesque um peixe e ganhe um prêmio!',
    category: 'jogos',
    image: '🎣',
    badge: 'Diversão',
    available: true,
    stallId: 'stall-5',
    variants: [{ id: 'pescaria-jogada', label: 'Jogada', price: 5.0, available: true }],
  },
  {
    id: 'argolas',
    name: 'Argolas',
    description: 'Acerte as argolas e ganhe brindes',
    category: 'jogos',
    image: '🎯',
    available: true,
    stallId: 'stall-5',
    variants: [{ id: 'argolas-jogada', label: 'Jogada', price: 5.0, available: true }],
  },
  {
    id: 'tiro-ao-alvo',
    name: 'Tiro ao Alvo',
    description: 'Teste sua pontaria!',
    category: 'jogos',
    image: '🎯',
    available: true,
    stallId: 'stall-5',
    variants: [{ id: 'tiro-ao-alvo-jogada', label: 'Jogada', price: 5.0, available: true }],
  },
  {
    id: 'bingo',
    name: 'Cartela de Bingo',
    description: 'Concorra a prêmios incríveis!',
    category: 'brincadeiras',
    image: '🎱',
    badge: 'Prêmios!',
    available: true,
    stallId: 'stall-6',
    variants: [{ id: 'bingo-cartela', label: 'Cartela', price: 5.0, available: true }],
  },
  {
    id: 'correio-elegante',
    name: 'Correio Elegante',
    description: 'Envie uma mensagem secreta para alguém especial',
    category: 'brincadeiras',
    image: '💌',
    badge: 'Romântico',
    available: true,
    stallId: 'stall-7',
    variants: [{ id: 'correio-elegante-mensagem', label: 'Mensagem', price: 3.0, available: true }],
  },
  {
    id: 'quadrilha',
    name: 'Quadrilha',
    description: 'Participe da dança tradicional',
    category: 'brincadeiras',
    image: '💃',
    badge: 'Grátis',
    available: true,
    stallId: 'stall-7',
    variants: [{ id: 'quadrilha-participacao', label: 'Participação', price: 0, available: true }],
  },
];

const menuProductsEvent2: Omit<MenuProduct, 'eventId'>[] = [
  {
    id: 'peru-assado',
    name: 'Peru Assado',
    description: 'Fatia generosa de peru assado com temperos natalinos',
    category: 'comidas',
    image: '🦃',
    badge: 'Especial',
    available: true,
    stallId: 'stall-n1',
    variants: [{ id: 'peru-assado-fatia', label: 'Fatia', price: 15.0, available: true }],
  },
  {
    id: 'panetone',
    name: 'Panetone',
    description: 'Fatia de panetone com frutas cristalizadas',
    category: 'doces',
    image: '🍞',
    available: true,
    stallId: 'stall-n2',
    variants: [{ id: 'panetone-fatia', label: 'Fatia', price: 8.0, available: true }],
  },
  {
    id: 'rabanada',
    name: 'Rabanada',
    description: 'Rabanada crocante com canela e açúcar',
    category: 'doces',
    image: '🍞',
    available: true,
    stallId: 'stall-n2',
    variants: [{ id: 'rabanada-unidade', label: 'Unidade', price: 5.0, available: true }],
  },
  {
    id: 'chocolate-quente',
    name: 'Chocolate Quente',
    description: 'Chocolate cremoso com marshmallow',
    category: 'bebidas',
    image: '☕',
    badge: 'Quentinho',
    available: true,
    stallId: 'stall-n3',
    variants: [{ id: 'chocolate-quente-copo', label: 'Copo', price: 7.0, available: true }],
  },
  {
    id: 'vinho-natal',
    name: 'Vinho Quente',
    description: 'Vinho temperado com especiarias natalinas',
    category: 'bebidas',
    image: '🍷',
    available: true,
    stallId: 'stall-n3',
    variants: [{ id: 'vinho-natal-copo', label: 'Copo', price: 9.0, available: true }],
  },
];

export const seedMenuProducts: MenuProduct[] = [
  ...menuProductsEvent1.map((p) => ({ ...p, eventId: '1' })),
  ...menuProductsEvent2.map((p) => ({ ...p, eventId: '2' })),
];

export function createDefaultMenuProductsForEvent(
  eventId: string,
  stallId: string
): MenuProduct[] {
  return [
    {
      id: `prod-${eventId}-welcome`,
      eventId,
      name: 'Item de boas-vindas',
      description: 'Adicione mais itens pelo painel administrativo',
      category: 'comidas',
      image: '🍽️',
      available: true,
      stallId,
      variants: [
        {
          id: `variant-${eventId}-welcome`,
          label: 'Unidade',
          price: 5,
          available: true,
        },
      ],
    },
  ];
}
